# Generated by Django 5.1.1 on 2024-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_student_avatar_student_email_student_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprogress",
            old_name="student",
            new_name="user",
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="completed_lessons",
            field=models.ManyToManyField(blank=True, to="courses.lesson"),
        ),
    ]
