# Generated by Django 5.1.1 on 2025-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_student_studentprogress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
