# Generated by Django 5.1.1 on 2025-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quizresult_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='stars',
            field=models.IntegerField(default=1, verbose_name='Звездочки за квиз'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='stars_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
