# Generated by Django 5.1.1 on 2025-05-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blocked_modules',
            field=models.ManyToManyField(blank=True, related_name='blocked_for_students', to='courses.module'),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students_set', to='courses.course'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('stars_penalty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='completed_quizzes',
            field=models.ManyToManyField(related_name='completed_by', through='courses.QuizAttempt', to='courses.quiz'),
        ),
    ]
