# Generated by Django 5.2.3 on 2025-06-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
