# Generated by Django 5.1.3 on 2025-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_student_temporary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео (например, YouTube)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
