# Generated by Django 5.2.3 on 2025-06-16 04:51

import courses.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lesson_video_url_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='convert_pdf_to_slides',
            field=models.BooleanField(default=False, help_text='Конвертировать PDF/PPTX в слайды для просмотра на странице'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='converted_slides_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('not_applicable', 'Неприменимо')], default='not_applicable', help_text='Статус конвертации PDF/PPTX в слайды', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slide_count',
            field=models.IntegerField(default=0, help_text='Количество сгенерированных слайдов'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео (YouTube, Vimeo, Google Drive, Dropbox, OneDrive)', max_length=500, null=True, validators=[courses.validators.validate_video_url]),
        ),
        migrations.CreateModel(
            name='LessonSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('order', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
