# Generated by Django 5.2.1 on 2025-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_lesson_convert_pdf_to_slides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_by_students', to='courses.module'),
        ),
    ]
