# Generated by Django 5.2.1 on 2025-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_studentmessagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessagerequest',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
