# Generated by Django 5.2.4 on 2025-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_studentmessagerequest_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('min_stars', models.PositiveIntegerField()),
                ('max_stars', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Уровень ученика',
                'verbose_name_plural': 'Уровни учеников',
                'ordering': ['number'],
            },
        ),
    ]
