# Generated by Django 5.2.4 on 2025-07-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
