# Generated by Django 5.2.4 on 2025-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_student_experience_remove_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course_approved', 'Курс добавлен'), ('course_rejected', 'Курс отклонён'), ('stars_awarded', 'Получены звёзды'), ('profile_edit', 'Редактирование профиля'), ('level_up', 'Повышение уровня')], max_length=30),
        ),
    ]
