# Generated by Django 5.2.4 on 2025-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, help_text='Описание уровня', null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение уровня (необязательно)', null=True, upload_to='levels/'),
        ),
    ]
