# Generated by Django 5.2.4 on 2025-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_level_description_level_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
