# Generated by Django 5.2.4 on 2025-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_quizattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_popup_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Критический')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course_approved', 'Курс добавлен'), ('course_rejected', 'Курс отклонён'), ('stars_awarded', 'Получены звёзды'), ('profile_edit', 'Редактирование профиля'), ('level_up', 'Повышение уровня'), ('quiz_started', 'Квиз начат'), ('quiz_completed', 'Квиз завершён'), ('group_added', 'Добавлен в группу'), ('rating_changed', 'Изменение в рейтинге'), ('request_approved', 'Запрос подтверждён'), ('request_rejected', 'Запрос отклонён')], max_length=30),
        ),
    ]
