# Generated by Django 4.2.7 on 2025-07-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_notification_extra_data_notification_is_popup_shown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ Очень плохо'), (2, '⭐⭐ Плохо'), (3, '⭐⭐⭐ Нормально'), (4, '⭐⭐⭐⭐ Хорошо'), (5, '⭐⭐⭐⭐⭐ Отлично')], help_text='Оценка курса от 1 до 5 звезд')),
                ('comment', models.TextField(blank=True, help_text='Комментарий о курсе', null=True, verbose_name='Отзыв')),
                ('what_liked', models.TextField(blank=True, help_text='Что понравилось в курсе', null=True, verbose_name='Что понравилось')),
                ('what_to_improve', models.TextField(blank=True, help_text='Что можно улучшить', null=True, verbose_name='Что улучшить')),
                ('would_recommend', models.BooleanField(default=True, help_text='Рекомендовали бы курс другим', verbose_name='Рекомендую другим')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedbacks', to='courses.student')),
            ],
            options={
                'verbose_name': 'Отзыв о курсе',
                'verbose_name_plural': 'Отзывы о курсах',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
