# Generated by Django 4.2.7 on 2025-07-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], help_text='Оценка курса от 1 до 5 звезд'),
        ),
    ]
