# Generated by Django 4.2.7 on 2025-07-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_coursefeedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stars',
            field=models.IntegerField(default=5, help_text='Количество звёзд, которые получит студент за завершение курса', verbose_name='Звёзды за курс'),
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('stars_given', models.BooleanField(default=False, verbose_name='Звёзды выданы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат курса',
                'verbose_name_plural': 'Результаты курсов',
                'ordering': ['-completed_date'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
