# Generated by Django 4.2.7 on 2025-08-13 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_course_stars_courseresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('passed_quizzes', 'Пройдено квизов (>=70%)'), ('perfect_quizzes', 'Квизы на 100%'), ('completed_courses', 'Завершено курсов'), ('total_stars', 'Накоплено звёзд'), ('level_reached', 'Достигнут уровень')], max_length=32)),
                ('condition_value', models.IntegerField()),
                ('reward', models.CharField(help_text='Название приза/награды (наклейки, футболка и т.д.)', max_length=255)),
                ('reward_icon', models.CharField(blank=True, default='🎁', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['condition_type', 'condition_value'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course_approved', 'Курс добавлен'), ('course_rejected', 'Курс отклонён'), ('stars_awarded', 'Получены звёзды'), ('profile_edit', 'Редактирование профиля'), ('level_up', 'Повышение уровня'), ('quiz_started', 'Квиз начат'), ('quiz_completed', 'Квиз завершён'), ('group_added', 'Добавлен в группу'), ('rating_changed', 'Изменение в рейтинге'), ('request_approved', 'Запрос подтверждён'), ('request_rejected', 'Запрос отклонён'), ('feedback_submitted', 'Отзыв отправлен'), ('achievement_unlocked', 'Открыто достижение')], max_length=30),
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_unlocked', to='courses.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='courses.student')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
