# Generated by Django 4.2.7 on 2025-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_achievement_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'Без темы'), ('course_approved', 'Курс добавлен'), ('course_rejected', 'Курс отклонён'), ('stars_awarded', 'Получены звёзды'), ('profile_edit', 'Редактирование профиля'), ('level_up', 'Повышение уровня'), ('quiz_started', 'Квиз начат'), ('quiz_completed', 'Квиз завершён'), ('group_added', 'Добавлен в группу'), ('rating_changed', 'Изменение в рейтинге'), ('request_approved', 'Запрос подтверждён'), ('request_rejected', 'Запрос отклонён'), ('feedback_submitted', 'Отзыв отправлен'), ('achievement_unlocked', 'Открыто достижение')], max_length=30),
        ),
    ]
