# Generated by Django 5.2.4 on 2025-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_school_student',
            field=models.BooleanField(default=True, verbose_name='Школьник'),
        ),
    ]
