# Generated by Django 5.2.4 on 2025-08-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
