# Generated by Django 5.2.4 on 2025-08-22 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseaddrequest',
            name='course',
        ),
        migrations.AddField(
            model_name='courseaddrequest',
            name='assigned_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Назначенный курс'),
        ),
        migrations.AddField(
            model_name='courseaddrequest',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название курса'),
        ),
    ]
