# Generated by Django 5.2.4 on 2025-08-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_user_is_teacher_teacher_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='courses.teacher', verbose_name='Преподаватель'),
        ),
    ]
