# Generated by Django 5.2.4 on 2025-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_remove_teacher_experience_years_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_quizzes', to='courses.student', verbose_name='Назначенные студенты'),
        ),
    ]
