# Generated by Django 4.2.7 on 2025-08-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_quiz_assigned_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание квиза'),
        ),
    ]
