# Generated by Django 5.2.4 on 2025-08-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_quiz_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='homework_files/', verbose_name='PDF файл')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL видео')),
                ('due_date', models.DateTimeField(verbose_name='Срок выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homeworks', to='courses.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий учителя')),
                ('grade', models.PositiveIntegerField(blank=True, help_text='Оценка от 1 до 10', null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.homework', verbose_name='Домашнее задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='courses.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Выполнение домашнего задания',
                'verbose_name_plural': 'Выполнения домашних заданий',
                'ordering': ['-created_at'],
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='homework_photos/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='courses.homeworksubmission', verbose_name='Выполнение')),
            ],
            options={
                'verbose_name': 'Фотография домашнего задания',
                'verbose_name_plural': 'Фотографии домашних заданий',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
