# Generated by Django 5.2.4 on 2025-08-25 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_homework_homeworksubmission_homeworkphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_date', models.DateField(auto_now_add=True)),
                ('stars_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_spins', to='courses.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'spin_date')},
            },
        ),
    ]
