# Generated by Django 5.2.4 on 2025-08-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_wheelspin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wheelspin',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wheelspin',
            name='spin_date',
        ),
    ]
